name: Deploy to Nekoweb and GH Pages (Backup host)

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nekoweb
      url: 'https://jbc.lol'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      - name: Install dependencies (using Bun)
        continue-on-error: true
        run: bun install
      - name: Install Playwright dependencies
        run: bunx playwright install chromium
      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Build jbsite
        continue-on-error: true
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NEKOWEB_APIKEY: '${{ secrets.NEKOWEB_APIKEY }}'
          NEKOWEB_COOKIE: '${{ secrets.NEKOWEB_COOKIE }}'
          COMMIT_HASH: '<a href="https://github.com/jbcarreon123/jbcarreon123.github.io/commit/${{ steps.commit.outputs.hash }}">${{ steps.commit.outputs.short }}</a>'
        run: DEBUG=pw:browser bun run build
      - name: Check if index.html exists
        run: cat ./dist/index.html
      - name: Upload generated files
        env:
          COPYPARTY_DEPLOY_KEY: ${{ secrets.COPYPARTY_DEPLOY_KEY }}
        run: |
          curl -o u2c.py https://raw.githubusercontent.com/9001/copyparty/refs/heads/hovudstraum/bin/u2c.py
          python3 ./u2c.py -a $COPYPARTY_DEPLOY_KEY --dr https://party.nomaakip.xyz/jbsite ./dist
      - name: Modify some stuff
        run: bun run ./mainsite.ts
      - name: Deploy on Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: 'dist/'
      - name: Rename not_found back to 404
        continue-on-error: true
        run: mv ./dist/not_found.html ./dist/404.html
      - name: deploy to wisp
        continue-on-error: true
        run: |
          curl https://sites.wisp.place/nekomimi.pet/wisp-cli-binaries/wisp-cli-x86_64-linux -o wisp-cli
          chmod +x wisp-cli
          ./wisp-cli \
            "$WISP_HANDLE" \
            --path "$SITE_PATH" \
            --site "$SITE_NAME" \
            --password "$WISP_APP_PASSWORD"
        env:
          SITE_PATH: 'dist'
          SITE_NAME: 'jb-site'
          WISP_HANDLE: 'jbc.lol'
          WISP_APP_PASSWORD: '${{ secrets.WISP_APP_PASSWORD }}'
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

  purge:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
            cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
            cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
            hosts: |
                jbc.lol
                gh.jbc.lol